_target_: src.model.Generator
in_channels: 80
upsample_initial_channel: 512
upsample_kernel_sizes: [16, 16, 4, 4]
resblock_kernel_sizes: [3, 7, 11]
resblock_dilations:
  - [[1, 1], [3, 1], [5, 1]]
  - [[1, 1], [3, 1], [5, 1]]
  - [[1, 1], [3, 1], [5, 1]]
