defaults:
  - model: hifigan_v1
  - writer: wandb
  - datasets: ruslan
  - dataloader: default
  - transforms: default
  - metrics: default
  - _self_

data_dir: "data/RUSLAN"

discriminator:
  _target_: src.model.Discriminator
  mpd_periods: [2, 3, 5, 7, 11]

mel_spectrogram:
  sr: 22050
  win_length: 1024
  hop_length: 256
  n_fft: 1024
  f_min: 0
  f_max: 11025
  n_mels: 80
  power: 2.0
  pad_value: -11.5129251

optimizer_g:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01

optimizer_d:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01

lr_scheduler_g:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

lr_scheduler_d:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: null
  device_tensors: ["audio"]
  resume_from: null
  from_pretrained: null
  device: auto
  override: True
  monitor: "min val_loss_mel"
  save_period: 5
  early_stop: 100
  save_dir: "results"
  seed: 42
  skip_oom: True
  max_grad_norm: null

lambda_fm: 2
lambda_mel: 45
