_target_: src.logger.WandBWriter
project_name: "hifigan_vocoder"
entity: null
run_name: "hifigan_v1"
mode: "online"
loss_names: ["loss_g", "loss_d", "loss_adv", "loss_fm", "loss_mel"]
log_checkpoints: False
id_length: 8
